#!/usr/bin/env bash
set -euo pipefail

auto_dir=".docker"
# Keep the generated auto-mode environment in .docker/auto.env so it stays
# ignored by git but can be reused by make urls/down/reset.
auto_env="${auto_dir}/auto.env"

mkdir -p "$auto_dir"

provided_project="${COMPOSE_PROJECT_NAME:-}"

if [[ -f ".env" ]]; then
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a
fi

if [[ -n "$provided_project" ]]; then
  project_name="$provided_project"
else
  repo_key="$(pwd -P | cksum | awk '{print $1}')"
  project_name="parapet_demo_${USER:-user}_${repo_key}"
  project_name="$(printf "%s" "$project_name" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9_-' '_')"
fi

port_available() {
  local port="$1"

  if command -v lsof >/dev/null 2>&1; then
    ! lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1
    return
  fi

  if command -v nc >/dev/null 2>&1; then
    ! nc -z 127.0.0.1 "$port" >/dev/null 2>&1
    return
  fi

  return 0
}

choose_port() {
  local start="$1"
  local end="$2"
  local salt="$3"
  local span=$((end - start + 1))
  local offset=$((salt % span))
  local candidate

  for i in $(seq 0 $((span - 1))); do
    candidate=$((start + ((offset + i) % span)))

    if port_available "$candidate"; then
      printf "%s" "$candidate"
      return 0
    fi
  done

  echo "No free localhost port found in range ${start}-${end}." >&2
  return 1
}

seed="$(printf "%s" "${project_name}" | cksum | awk '{print $1}')"
web_port="$(choose_port 4100 4999 "$seed")"
grafana_port="$(choose_port 5100 5999 "$((seed + 17))")"
prometheus_port="$(choose_port 6100 6999 "$((seed + 31))")"

cat >"$auto_env" <<EOF
# Generated by scripts/prepare_auto_env.sh. Do not edit.
COMPOSE_PROJECT_NAME=${project_name}
WEB_PORT=${web_port}
GRAFANA_PORT=${grafana_port}
PROMETHEUS_PORT=${prometheus_port}
PARAPET_DEMO_GRAFANA_URL=http://127.0.0.1:${grafana_port}
EOF

cat <<EOF
Generated ${auto_env}:
  Compose project: ${project_name}
  Web port:        ${web_port}
  Grafana port:    ${grafana_port}
  Prometheus port: ${prometheus_port}
EOF
