defmodule Parapet.Repo.Migrations.MoveParapetSpineToSchema do
  @moduledoc """
  Reversible single-transaction migration moving the six Parapet spine tables
  from the `public` schema into the `parapet` schema (Track B upgrade path).

  Generated by `mix parapet.gen.schema.move` with the default `--schema parapet`
  options (create_schema: true). This is a committed fixture shared by:

    - `test/parapet/gen_schema_move_golden_test.exs` — DB-less shape assertions
    - `test/parapet/repo/migrations/move_spine_to_parapet_schema_test.exs` — up/down round-trip

  Do NOT generate a second move migration on top of this file.
  """
  use Ecto.Migration

  # after_begin/0 fires on BOTH up and down — written once, D-08 Pattern 3.
  # SET LOCAL is transaction-scoped: bounds every SET SCHEMA's ACCESS EXCLUSIVE
  # lock acquisition so a blocked move fails fast instead of queuing prod traffic.
  def after_begin do
    repo().query!("SET LOCAL lock_timeout TO '5s'")
  end

  def up do
    # -----------------------------------------------------------------------
    # Migrate-time abort guard (D-10, UPG-03):
    # Raises BEFORE any SET SCHEMA if any of the six public.<t> tables is
    # missing or renamed. Nothing moves on failure — we're inside the txn.
    # Uses to_regclass (returns NULL on absent, not an error) + quote_ident.
    # Table list is a fixed literal ARRAY, never user input (T-54-05).
    # -----------------------------------------------------------------------
    execute("""
    DO $$
    DECLARE t text;
    BEGIN
      FOREACH t IN ARRAY ARRAY['parapet_action_items','parapet_incidents','parapet_timeline_entries',
                               'parapet_tool_audits','parapet_system_events','parapet_action_claims'] LOOP
        IF to_regclass('public.' || quote_ident(t)) IS NULL THEN
          RAISE EXCEPTION 'Parapet spine table public.% not found. If you renamed Parapet tables, '
            'edit this migration''s table list before migrating.', t;
        END IF;
      END LOOP;
    END $$;
    """)

    # -----------------------------------------------------------------------
    # Non-blocking inbound FK / view advisory (D-10, UPG-03):
    # PG moves intra-spine FKs automatically; cross-schema FKs from adopter
    # tables remain valid. Only views/rules referencing spine tables by
    # unqualified name may silently rebind after the move. This is a NOTICE,
    # not an abort — the adopter reviews and re-qualifies affected views.
    # -----------------------------------------------------------------------
    execute("""
    DO $$
    DECLARE r record;
    BEGIN
      FOR r IN
        SELECT DISTINCT view_name
        FROM information_schema.view_table_usage
        WHERE table_schema = 'public'
          AND table_name IN ('parapet_action_items','parapet_incidents',
                             'parapet_timeline_entries','parapet_tool_audits',
                             'parapet_system_events','parapet_action_claims')
      LOOP
        RAISE NOTICE 'View % references a Parapet spine table being moved. '
          'Review and re-qualify its definition after this migration to avoid '
          'silent rebinding.', r.view_name;
      END LOOP;
    END $$;
    """)

    execute("CREATE SCHEMA IF NOT EXISTS parapet")

    # Six explicit SET SCHEMA lines (D-08, D-09):
    # NOT a for-loop — a prod PR must `grep parapet_incidents migration.exs`
    # and hit this moved line. Fully-qualified source: public.<t> (D-09).
    execute("ALTER TABLE public.parapet_action_items SET SCHEMA parapet")
    execute("ALTER TABLE public.parapet_incidents SET SCHEMA parapet")
    execute("ALTER TABLE public.parapet_timeline_entries SET SCHEMA parapet")
    execute("ALTER TABLE public.parapet_tool_audits SET SCHEMA parapet")
    execute("ALTER TABLE public.parapet_system_events SET SCHEMA parapet")
    execute("ALTER TABLE public.parapet_action_claims SET SCHEMA parapet")
  end

  def down do
    # Six explicit reverse SET SCHEMA lines in LIFO order (D-08, D-09).
    # Fully-qualified source: parapet.<t> (D-09 — never rely on search_path).
    execute("ALTER TABLE parapet.parapet_action_claims SET SCHEMA public")
    execute("ALTER TABLE parapet.parapet_system_events SET SCHEMA public")
    execute("ALTER TABLE parapet.parapet_tool_audits SET SCHEMA public")
    execute("ALTER TABLE parapet.parapet_timeline_entries SET SCHEMA public")
    execute("ALTER TABLE parapet.parapet_incidents SET SCHEMA public")
    execute("ALTER TABLE parapet.parapet_action_items SET SCHEMA public")
    # NOTE: Deliberately no DROP SCHEMA here (fail-closed, D-08).
    # The target schema may contain other Parapet objects (e.g. from the sentinel
    # migration). DROP SCHEMA belongs to the sentinel migration's down/0, or a DBA.
  end
end
