groups:

  - name: parapet_slo_http
    rules:

      - record: slo:error_ratio:rate5m
        expr: >
          1 - (
            sum(rate(parapet_http_server_duration_milliseconds_count{status_code=~"2..|3.."}[5m]))
            /
            sum(rate(parapet_http_server_duration_milliseconds_count[5m]))
          )
        labels:
          slo: http

      - record: slo:error_ratio:rate30m
        expr: >
          1 - (
            sum(rate(parapet_http_server_duration_milliseconds_count{status_code=~"2..|3.."}[30m]))
            /
            sum(rate(parapet_http_server_duration_milliseconds_count[30m]))
          )
        labels:
          slo: http

      - record: slo:error_ratio:rate1h
        expr: >
          1 - (
            sum(rate(parapet_http_server_duration_milliseconds_count{status_code=~"2..|3.."}[1h]))
            /
            sum(rate(parapet_http_server_duration_milliseconds_count[1h]))
          )
        labels:
          slo: http

      - record: slo:error_ratio:rate2h
        expr: >
          1 - (
            sum(rate(parapet_http_server_duration_milliseconds_count{status_code=~"2..|3.."}[2h]))
            /
            sum(rate(parapet_http_server_duration_milliseconds_count[2h]))
          )
        labels:
          slo: http

      - record: slo:error_ratio:rate6h
        expr: >
          1 - (
            sum(rate(parapet_http_server_duration_milliseconds_count{status_code=~"2..|3.."}[6h]))
            /
            sum(rate(parapet_http_server_duration_milliseconds_count[6h]))
          )
        labels:
          slo: http

      - record: slo:error_ratio:rate3d
        expr: >
          1 - (
            sum(rate(parapet_http_server_duration_milliseconds_count{status_code=~"2..|3.."}[3d]))
            /
            sum(rate(parapet_http_server_duration_milliseconds_count[3d]))
          )
        labels:
          slo: http


  - name: parapet_slo_oban
    rules:

      - record: slo:error_ratio:rate5m
        expr: >
          1 - (
            sum(rate(parapet_oban_job_duration_milliseconds_count{state="success"}[5m]))
            /
            sum(rate(parapet_oban_job_duration_milliseconds_count[5m]))
          )
        labels:
          slo: oban

      - record: slo:error_ratio:rate30m
        expr: >
          1 - (
            sum(rate(parapet_oban_job_duration_milliseconds_count{state="success"}[30m]))
            /
            sum(rate(parapet_oban_job_duration_milliseconds_count[30m]))
          )
        labels:
          slo: oban

      - record: slo:error_ratio:rate1h
        expr: >
          1 - (
            sum(rate(parapet_oban_job_duration_milliseconds_count{state="success"}[1h]))
            /
            sum(rate(parapet_oban_job_duration_milliseconds_count[1h]))
          )
        labels:
          slo: oban

      - record: slo:error_ratio:rate2h
        expr: >
          1 - (
            sum(rate(parapet_oban_job_duration_milliseconds_count{state="success"}[2h]))
            /
            sum(rate(parapet_oban_job_duration_milliseconds_count[2h]))
          )
        labels:
          slo: oban

      - record: slo:error_ratio:rate6h
        expr: >
          1 - (
            sum(rate(parapet_oban_job_duration_milliseconds_count{state="success"}[6h]))
            /
            sum(rate(parapet_oban_job_duration_milliseconds_count[6h]))
          )
        labels:
          slo: oban

      - record: slo:error_ratio:rate3d
        expr: >
          1 - (
            sum(rate(parapet_oban_job_duration_milliseconds_count{state="success"}[3d]))
            /
            sum(rate(parapet_oban_job_duration_milliseconds_count[3d]))
          )
        labels:
          slo: oban


  - name: parapet_slo_login_journey
    rules:

      - record: slo:error_ratio:rate5m
        expr: >
          1 - (
            sum(rate(parapet_journey_login_duration_milliseconds_count{outcome="success"}[5m]))
            /
            sum(rate(parapet_journey_login_duration_milliseconds_count[5m]))
          )
        labels:
          slo: login_journey

      - record: slo:error_ratio:rate30m
        expr: >
          1 - (
            sum(rate(parapet_journey_login_duration_milliseconds_count{outcome="success"}[30m]))
            /
            sum(rate(parapet_journey_login_duration_milliseconds_count[30m]))
          )
        labels:
          slo: login_journey

      - record: slo:error_ratio:rate1h
        expr: >
          1 - (
            sum(rate(parapet_journey_login_duration_milliseconds_count{outcome="success"}[1h]))
            /
            sum(rate(parapet_journey_login_duration_milliseconds_count[1h]))
          )
        labels:
          slo: login_journey

      - record: slo:error_ratio:rate2h
        expr: >
          1 - (
            sum(rate(parapet_journey_login_duration_milliseconds_count{outcome="success"}[2h]))
            /
            sum(rate(parapet_journey_login_duration_milliseconds_count[2h]))
          )
        labels:
          slo: login_journey

      - record: slo:error_ratio:rate6h
        expr: >
          1 - (
            sum(rate(parapet_journey_login_duration_milliseconds_count{outcome="success"}[6h]))
            /
            sum(rate(parapet_journey_login_duration_milliseconds_count[6h]))
          )
        labels:
          slo: login_journey

      - record: slo:error_ratio:rate3d
        expr: >
          1 - (
            sum(rate(parapet_journey_login_duration_milliseconds_count{outcome="success"}[3d]))
            /
            sum(rate(parapet_journey_login_duration_milliseconds_count[3d]))
          )
        labels:
          slo: login_journey
